version: '3.4'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    container_name: web_scraping
    volumes:
      - .:/web_scraping
    ports:
      - "8000:8000"
    depends_on:
      - db